name: CI

on: [push]

jobs:

  format:
    name: Format (Black)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.7.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install black
    - name: Run Black
      run: black app/ --check

  lint:
    name: Lint (Flake8)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.7.6
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install flake8
    - name: Run Flake8
      run: flake8 app/
